from .auth import (
    AuditLog,
    FailedLoginAttempt,
    Permission,
    PendingRegistration,
    RefreshToken,
    Role,
    User,
    role_permissions,
    user_roles,
)

from .documents import (
    Document,
    DocumentChunk,
    DocumentProcessingJob,
    DocumentRelation,
    DocumentReview,
    DocumentTopic,
    DocumentVersion,
)

from .advisor import (
    ChatMessage,
    Conversation,
    MessageCitation,
    MessageFeedback,
    RetrievalLog,
)

from .consultations import (
    ConsultationBooking,
    ConsultantProfile,
    ConsultantReview,
    ConsultantSettlement,
    ConsultantVerificationRequest,
    ConsultationRequest,
    ConsultationStatusHistory,
)

from .portal import (
    DiscountCode,
    LawReferenceRecord,
    LegalCategory,
    LegalExternalSource,
    LegalUpdateCandidate,
    Payment,
    PaymentMethod,
    PaymentOtpChallenge,
    PhoneVerificationChallenge,
    SubscriptionPlan,
    SupportTicket,
    TaxReminder,
    TicketMessage,
    ToolUsageEvent,
    UserDocument,
    UserNotification,
    UserProfile,
    UserSubscription,
    WalletAccount,
    WalletTransaction,
)

from .site import (
    ContentComment,
    ContentPage,
    SiteConfiguration,
    SiteConfigurationVersion,
)


__all__ = [
    "AuditLog",
    "FailedLoginAttempt",
    "Permission",
    "PendingRegistration",
    "RefreshToken",
    "Role",
    "User",
    "role_permissions",
    "user_roles",
    "Document",
    "DocumentChunk",
    "DocumentProcessingJob",
    "DocumentRelation",
    "DocumentReview",
    "DocumentTopic",
    "DocumentVersion",
    "ChatMessage",
    "Conversation",
    "MessageCitation",
    "MessageFeedback",
    "RetrievalLog",
    "ConsultationRequest",
    "ConsultationStatusHistory",
    "ConsultantProfile",
    "ConsultantVerificationRequest",
    "ConsultationBooking",
    "ConsultantReview",
    "ConsultantSettlement",
    "UserProfile",
    "PhoneVerificationChallenge",
    "SubscriptionPlan",
    "UserSubscription",
    "PaymentMethod",
    "PaymentOtpChallenge",
    "Payment",
    "DiscountCode",
    "UserDocument",
    "SupportTicket",
    "TicketMessage",
    "TaxReminder",
    "ToolUsageEvent",
    "LawReferenceRecord",
    "LegalCategory",
    "LegalExternalSource",
    "LegalUpdateCandidate",
    "WalletAccount",
    "WalletTransaction",
    "UserNotification",
    "SiteConfiguration",
    "SiteConfigurationVersion",
    "ContentPage",
    "ContentComment",
]