"use client";

import { FormEvent, useState } from "react";
import { FileUp, LockKeyhole } from "lucide-react";
import { api, ApiError } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

export type UserDocument = { id:string; title:string; document_type:string; description:string; purpose:string; intended_reviewer:string; filename:string; file_size:number; status:string; admin_note:string; reviewed_at?:string|null; created_at:string };
export const documentTypes = [["national_card","کارت ملی"],["education_certificate","مدرک تحصیلی مرتبط"],["professional_license","مجوز یا گواهی حرفه‌ای"],["resume","رزومه حرفه‌ای"],["company_registration","آگهی ثبت یا آخرین تغییرات شرکت"],["company_national_id","شناسه ملی شرکت"],["representative_card","کارت ملی نماینده شرکت"],["tax_document","سند یا اظهارنامه مالیاتی"],["financial_statement","صورت مالی"],["contract","قرارداد"],["other","سایر مدارک"]] as const;
const purposes = [["consultant_verification","احراز صلاحیت مشاور"],["tax_case_review","بررسی پرونده مالیاتی"],["document_analysis","تحلیل سند"],["support_request","درخواست پشتیبانی"],["general_review","بررسی عمومی"]] as const;
const reviewers = [["consultant_management","واحد مدیریت مشاوران"],["tax_expert","کارشناس مالیاتی"],["support","واحد پشتیبانی"],["system_admin","مدیر سامانه"]] as const;

export function UserDocumentUploader({presetPurpose="general_review",presetReviewer="support",presetType="other",compact=false,onUploaded}:{presetPurpose?:string;presetReviewer?:string;presetType?:string;compact?:boolean;onUploaded?:(document:UserDocument)=>void}){
  const[title,setTitle]=useState(""),[documentType,setDocumentType]=useState(presetType),[description,setDescription]=useState(""),[purpose,setPurpose]=useState(presetPurpose),[reviewer,setReviewer]=useState(presetReviewer),[file,setFile]=useState<File|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  async function submit(event:FormEvent){event.preventDefault();if(!file)return;setBusy(true);setMessage("");const form=new FormData();form.set("title",title);form.set("document_type",documentType);form.set("description",description);form.set("purpose",purpose);form.set("intended_reviewer",reviewer);form.set("file",file);try{const created=await api<UserDocument>("api/v1/portal/documents",{method:"POST",body:form});setTitle("");setDescription("");setFile(null);setMessage("سند با موفقیت و به‌صورت محرمانه بارگذاری شد.");onUploaded?.(created)}catch(error){setMessage(error instanceof ApiError?error.message:"بارگذاری سند انجام نشد.")}finally{setBusy(false)}}
  return <form onSubmit={submit} className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><label className="space-y-1.5 text-sm"><span className="font-bold">نوع سند</span><select value={documentType} onChange={event=>setDocumentType(event.target.value)} className="h-10 w-full rounded-lg border bg-white px-3">{documentTypes.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="space-y-1.5 text-sm"><span className="font-bold">عنوان قابل تشخیص</span><Input value={title} onChange={event=>setTitle(event.target.value)} placeholder="مثلاً کارت ملی امیر غلامی" required minLength={3}/></label></div>{!compact&&<div className="grid gap-3 sm:grid-cols-2"><label className="space-y-1.5 text-sm"><span className="font-bold">برای چه کاری؟</span><select value={purpose} onChange={event=>setPurpose(event.target.value)} className="h-10 w-full rounded-lg border bg-white px-3">{purposes.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="space-y-1.5 text-sm"><span className="font-bold">بررسی توسط</span><select value={reviewer} onChange={event=>setReviewer(event.target.value)} className="h-10 w-full rounded-lg border bg-white px-3">{reviewers.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div>}<label className="block space-y-1.5 text-sm"><span className="font-bold">توضیح برای بررسی‌کننده</span><Textarea value={description} onChange={event=>setDescription(event.target.value)} placeholder="این سند مربوط به کدام پرونده یا درخواست است و چه نکته‌ای باید بررسی شود؟" required minLength={5} className="min-h-24"/></label><label className="block space-y-1.5 text-sm"><span className="font-bold">انتخاب فایل</span><Input type="file" accept=".pdf,.docx,.xlsx,.txt,.jpg,.jpeg,.png,.webp" onChange={event=>setFile(event.target.files?.[0]??null)} required/><span className="block text-xs text-slate-500">PDF، Word، Excel، تصویر یا متن؛ حداکثر ۲۰ مگابایت.</span></label><Button type="submit" className="w-full" disabled={busy}><FileUp/>{busy?"در حال بارگذاری...":"بارگذاری امن سند"}</Button><p className="flex gap-2 text-xs leading-6 text-muted-foreground"><LockKeyhole className="mt-1 size-4 shrink-0"/>فایل فقط برای واحد انتخاب‌شده و مدیران مجاز قابل مشاهده است.</p>{message&&<p role="status" className="rounded-lg bg-primary/5 p-3 text-sm">{message}</p>}</form>;
}
