import Link from "next/link";
import { ArrowLeft, BadgeCheck, Building2, CalendarCheck, Headphones, MessageCircle, Star, UserRoundSearch } from "lucide-react";

export default function ConsultationsPage() {
  return <div className="space-y-8"><header className="relative overflow-hidden rounded-[2rem] bg-gradient-to-l from-blue-700 via-blue-600 to-cyan-500 p-8 text-white shadow-xl shadow-blue-900/15"><div className="absolute -left-16 -top-20 size-56 rounded-full bg-white/10" /><div className="relative"><p className="text-sm text-blue-50">مرکز مشاوره چکاه</p><h1 className="mt-2 text-3xl font-black">مسیر مشاوره مناسب خود را انتخاب کنید</h1><p className="mt-3 max-w-2xl leading-8 text-blue-50">پاسخ سریع آنلاین از تیم چکاه یا رزرو اختصاصی با مشاوران مستقل و تأییدشده.</p></div></header><section className="grid gap-6 lg:grid-cols-2"><ConsultationType href="/app/consultations/company" icon={Building2} title="مشاوران آنلاین شرکت چکاه" badge="پاسخ آنلاین" description="برای پرسش‌ها و پرونده‌های روزمره؛ تا سقف پلن رایگان و سپس قابل ادامه با کیف پول." color="from-blue-600 to-cyan-500" features={["سهمیه رایگان ماهانه", "پاسخ‌گویی فقط آنلاین", "ارجاع خودکار به کارشناس شرکت"]} /><ConsultationType href="/app/consultations/independent" icon={UserRoundSearch} title="مشاوران مستقل مالیاتی" badge="رزرو اختصاصی" description="مشاور را بر اساس تخصص، شهر، امتیاز و زمان آزاد انتخاب و نوبت خود را رزرو کنید." color="from-orange-500 to-rose-500" features={["پروفایل و رزومه کامل", "تقویم رزرو اختصاصی", "مشاوره حضوری یا آنلاین", "ویژه کاربران پلن پلاس و حرفه‌ای"]} /></section><div className="grid gap-4 sm:grid-cols-3"><Mini icon={BadgeCheck} text="مشاوران تأییدشده" /><Mini icon={CalendarCheck} text="رزرو زمان مشخص" /><Mini icon={Headphones} text="پیگیری یکپارچه" /></div></div>;
}

function ConsultationType({ href, icon: Icon, title, badge, description, color, features }: { href: string; icon: typeof Building2; title: string; badge: string; description: string; color: string; features: string[] }) { return <Link href={href} className="group overflow-hidden rounded-[2rem] border border-sky-100 bg-white shadow-xl shadow-slate-900/5 transition hover:-translate-y-1 hover:shadow-2xl"><div className={`h-2 bg-gradient-to-l ${color}`} /><div className="p-7"><div className="flex items-start justify-between"><span className={`flex size-14 items-center justify-center rounded-2xl bg-gradient-to-br text-white ${color}`}><Icon /></span><span className="rounded-full bg-sky-50 px-3 py-1 text-xs font-bold text-blue-700">{badge}</span></div><h2 className="mt-6 text-2xl font-black">{title}</h2><p className="mt-3 min-h-16 text-sm leading-7 text-slate-500">{description}</p><div className="mt-5 space-y-3">{features.map((feature) => <p key={feature} className="flex items-center gap-2 text-sm"><Star className="size-4 text-amber-500" />{feature}</p>)}</div><span className="mt-7 flex items-center justify-center gap-2 rounded-2xl bg-gradient-to-l from-blue-600 to-cyan-500 px-5 py-3 text-sm font-bold text-white transition group-hover:shadow-lg">ورود به بخش <ArrowLeft className="size-4" /></span></div></Link>; }
function Mini({ icon: Icon, text }: { icon: typeof MessageCircle; text: string }) { return <div className="flex items-center gap-3 rounded-2xl border border-sky-100 bg-sky-50/60 p-4"><Icon className="text-blue-600" /><p className="text-sm font-bold">{text}</p></div>; }
