"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { Download, Search, ShieldCheck, UserCheck, Users, WalletCards } from "lucide-react";
import { api, ApiError } from "@/lib/api";
import type { User } from "@/lib/types";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

type Profile = { id:string; phone:string; province:string; city:string; company_name:string; job_title:string; profile_score:number; reward_points:number };
type Wallet = { user_id:string; balance:number; total_deposited:number; total_spent:number; total_withdrawn:number };
type UnifiedUser = User & { profile?:Profile; wallet?:Wallet };
const roleLabels:Record<string,string> = { user:"کاربر", admin:"ادمین", tax_expert:"کارشناس مالی", company_expert:"کارشناس شرکت", system_admin:"مدیر سامانه" };
const tierLabels = { normal:"عادی", plus:"پلاس", pro:"حرفه‌ای" };

export default function UserManagementPage() {
  const [items,setItems] = useState<UnifiedUser[]>([]); const [query,setQuery] = useState(""); const [status,setStatus] = useState("all"); const [loading,setLoading] = useState(true); const [error,setError] = useState("");
  useEffect(() => { Promise.all([api<User[]>("users?limit=100"), api<Profile[]>("api/v1/admin/profiles"), api<Wallet[]>("api/v1/admin/wallets?limit=100")]).then(([users,profiles,wallets]) => setItems(users.map((user) => ({...user,profile:profiles.find((item) => item.id===user.id),wallet:wallets.find((item) => item.user_id===user.id)})))).catch((reason) => setError(reason instanceof ApiError ? reason.message : "دریافت اطلاعات کاربران ممکن نیست.")).finally(() => setLoading(false)); }, []);
  const filtered = useMemo(() => items.filter((item) => { const text = `${item.full_name} ${item.email} ${item.profile?.phone || ""} ${item.profile?.company_name || ""}`.toLowerCase(); return text.includes(query.toLowerCase()) && (status === "all" || (status === "active" ? item.is_active : !item.is_active)); }), [items,query,status]);
  return <div className="space-y-7"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold text-primary">مرکز یکپارچه کاربران</p><h1 className="mt-2 text-3xl font-black">کاربران، پروفایل و کیف پول</h1><p className="mt-2 text-muted-foreground">تمام اطلاعات حساب، تماس، اشتراک، موجودی و فعالیت هر کاربر از یک صفحه در دسترس است.</p></div><a href="/api/backend/api/v1/admin/export/users.xlsx" className="flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white"><Download className="size-4"/>خروجی اکسل</a></header>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={Users} label="کل کاربران" value={items.length}/><Metric icon={UserCheck} label="کاربر فعال" value={items.filter((item)=>item.is_active).length}/><Metric icon={ShieldCheck} label="مدیران" value={items.filter((item)=>item.roles.some((role)=>["admin","system_admin"].includes(role))).length}/><Metric icon={WalletCards} label="مجموع موجودی" value={`${items.reduce((sum,item)=>sum+(item.wallet?.balance||0),0).toLocaleString("fa-IR")} تومان`}/></div>
    <div className="flex flex-wrap gap-3"><label className="relative min-w-64 flex-1"><Search className="absolute right-3 top-3 size-4 text-slate-400"/><Input className="pr-10" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="نام، ایمیل، موبایل یا کسب‌وکار"/></label><select value={status} onChange={(event)=>setStatus(event.target.value)} className="h-10 rounded-lg border bg-white px-4 text-sm"><option value="all">همه وضعیت‌ها</option><option value="active">فعال</option><option value="inactive">غیرفعال</option></select></div>
    {error && <p className="rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{error}</p>}
    <Card className="overflow-hidden"><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-right text-sm"><thead className="border-b bg-slate-50 text-slate-500"><tr><th className="p-4">کاربر</th><th className="p-4">تماس و موقعیت</th><th className="p-4">نقش</th><th className="p-4">پلن</th><th className="p-4">کیف پول</th><th className="p-4">پروفایل</th><th className="p-4">وضعیت</th><th className="p-4">عملیات</th></tr></thead><tbody className="divide-y">{filtered.map((item)=><tr key={item.id} className="transition hover:bg-blue-50/30"><td className="p-4"><p className="font-bold">{item.full_name}</p><p className="mt-1 text-xs text-muted-foreground" dir="ltr">{item.email}</p></td><td className="p-4"><p dir="ltr" className="text-right">{item.profile?.phone || "—"}</p><p className="mt-1 text-xs text-muted-foreground">{[item.profile?.province,item.profile?.city].filter(Boolean).join("، ") || "ثبت نشده"}</p></td><td className="p-4">{item.roles.map((role)=><Badge key={role} variant="outline" className="ml-1">{roleLabels[role] || role}</Badge>)}</td><td className="p-4"><Badge>{tierLabels[item.account_tier]}</Badge></td><td className="p-4 font-black text-blue-700">{(item.wallet?.balance||0).toLocaleString("fa-IR")} تومان</td><td className="p-4">{(item.profile?.profile_score||10).toLocaleString("fa-IR")}٪</td><td className="p-4"><span className={`rounded-full px-3 py-1 text-xs ${item.is_active?"bg-emerald-50 text-emerald-700":"bg-rose-50 text-rose-700"}`}>{item.is_active?"فعال":"غیرفعال"}</span></td><td className="p-4"><Link href={`/management/users/${item.id}`} className="rounded-lg bg-blue-600 px-3 py-2 text-xs font-bold text-white">مشاهده و ویرایش</Link></td></tr>)}</tbody></table></div>{loading && <p className="p-12 text-center text-muted-foreground">در حال دریافت کاربران...</p>}{!loading && !filtered.length && <p className="p-12 text-center text-muted-foreground">کاربری پیدا نشد.</p>}</CardContent></Card>
  </div>;
}
function Metric({icon:Icon,label,value}:{icon:typeof Users;label:string;value:string|number}) { return <Card><CardContent className="flex items-center gap-3 p-5"><span className="rounded-xl bg-blue-50 p-3 text-blue-700"><Icon className="size-5"/></span><div><p className="text-xl font-black">{typeof value==="number"?value.toLocaleString("fa-IR"):value}</p><p className="text-xs text-muted-foreground">{label}</p></div></CardContent></Card>; }
