"use client";

import { useEffect, useState } from "react";
import { Bell, Bot, Calculator, FileSearch, FileSignature, FileText, Gift, Headphones, TicketCheck, Users } from "lucide-react";
import { api } from "@/lib/api";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

type Usage = { tier: string; used: Record<string, number>; limits: Record<string, number> };
type Wallet = { points: number; referral_code: string; successful_referrals: number; rewards: { points: number; title: string }[] };
type Notification = { id: string; title: string; due_date: string; days_remaining: number; severity: string };
const items = [["questions", "پرسش هوش مصنوعی", Bot], ["law_search", "جست‌وجوی قوانین", FileSearch], ["calculator", "محاسبه مالیاتی", Calculator], ["letters", "نامه و لایحه", FileSignature], ["documents", "اسناد", FileText], ["tickets", "تیکت فعال", TicketCheck], ["consultations", "مشاوره تخصصی", Headphones]] as const;

export default function UsagePage() {
  const [usage, setUsage] = useState<Usage | null>(null); const [wallet, setWallet] = useState<Wallet | null>(null); const [notifications, setNotifications] = useState<Notification[]>([]);
  useEffect(() => { Promise.all([api<Usage>("api/v1/tools/usage"), api<Wallet>("api/v1/tools/wallet"), api<Notification[]>("api/v1/tools/notifications")]).then(([usageData, walletData, notificationData]) => { setUsage(usageData); setWallet(walletData); setNotifications(notificationData); }); }, []);
  return <div className="space-y-7"><header><p className="text-sm font-medium text-primary">گزارش حساب</p><h1 className="mt-1 text-3xl font-black">مصرف پلن، اعلان و امتیاز</h1><p className="mt-2 text-muted-foreground">ظرفیت باقی‌مانده و پاداش‌های حساب را یکجا ببینید.</p></header><section className="grid gap-4 md:grid-cols-2">{items.map(([key, label, Icon]) => { const used = usage?.used[key] ?? 0; const limit = usage?.limits[key] ?? 1; const percent = Math.min(100, used / limit * 100); return <Card key={key} className="border-white/70 bg-white/85"><CardContent className="p-5"><div className="flex items-center gap-3"><span className="flex size-11 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon /></span><div className="flex-1"><div className="flex justify-between"><p className="font-semibold">{label}</p><p className="text-sm">{used.toLocaleString("fa-IR")} از {limit.toLocaleString("fa-IR")}</p></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-primary" style={{ width: `${percent}%` }} /></div></div></div></CardContent></Card>; })}</section><div className="grid gap-6 lg:grid-cols-2"><Card className="border-0 bg-slate-950 text-white"><CardHeader><CardTitle className="flex gap-2"><Gift className="text-amber-300" /> کیف امتیاز</CardTitle><CardDescription className="text-slate-400">با تکمیل پروفایل و دعوت دوستان امتیاز بگیرید.</CardDescription></CardHeader><CardContent><p className="text-4xl font-black text-teal-300">{(wallet?.points ?? 0).toLocaleString("fa-IR")}</p><p className="mt-1 text-sm text-slate-400">امتیاز قابل استفاده</p><div className="mt-5 rounded-xl bg-white/5 p-4"><p className="text-xs text-slate-400">کد معرف شما</p><p className="mt-1 font-mono text-xl">{wallet?.referral_code || "—"}</p><p className="mt-2 flex gap-1 text-xs text-slate-400"><Users className="size-3.5" /> {wallet?.successful_referrals ?? 0} دعوت موفق</p></div></CardContent></Card><Card className="border-white/70 bg-white/85"><CardHeader><CardTitle className="flex gap-2"><Bell className="text-primary" /> اعلان‌های نزدیک</CardTitle></CardHeader><CardContent className="space-y-2">{notifications.map((item) => <div key={item.id} className="rounded-xl bg-amber-50 p-3 text-sm"><p className="font-semibold">{item.title}</p><p className="mt-1 text-xs text-amber-800">{item.days_remaining < 0 ? `${Math.abs(item.days_remaining)} روز گذشته` : `${item.days_remaining} روز باقی مانده`}</p></div>)}{!notifications.length && <p className="py-8 text-center text-sm text-muted-foreground">اعلان فعالی ندارید.</p>}</CardContent></Card></div></div>;
}
