"use client";

import { useEffect, useMemo, useState } from "react";
import { Edit3, Search, UserRoundSearch, X } from "lucide-react";
import { api, ApiError } from "@/lib/api";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

type Row = { id: string; full_name: string; email: string; tier: string; is_active: boolean; phone_verified: boolean; profile_score: number; reward_points: number; [key: string]: string | number | boolean | null };
const editable = [
  ["phone","موبایل"],["alternate_phone","تماس جایگزین"],["alternate_email","ایمیل اختیاری"],["province","استان"],["city","شهر"],["postal_code","کد پستی"],["birth_date","تاریخ تولد"],
  ["company_name","شرکت یا کسب‌وکار"],["job_title","عنوان شغلی"],["business_type","نوع فعالیت"],["economic_code","کد اقتصادی"],["website","وب‌سایت"],
] as const;

export default function ProfilesPage() {
  const [rows, setRows] = useState<Row[]>([]); const [query, setQuery] = useState(""); const [selected, setSelected] = useState<Row | null>(null); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { api<Row[]>("api/v1/admin/profiles").then(setRows).catch((e) => setMessage(e instanceof ApiError ? e.message : "دریافت کاربران ممکن نیست.")); }, []);
  const filtered = useMemo(() => rows.filter((row) => `${row.full_name} ${row.email} ${row.phone || ""} ${row.company_name || ""}`.toLowerCase().includes(query.toLowerCase())), [query, rows]);
  function change(key: string, value: string | number | boolean | null) { setSelected((current) => current ? { ...current, [key]: value } : current); }
  async function save() { if (!selected) return; setSaving(true); try { const payload = Object.fromEntries([...editable.map(([key]) => [key, selected[key] || ""]), ["address", selected.address || ""], ["bio", selected.bio || ""], ["taxpayer_type", selected.taxpayer_type || "individual"], ["preferred_contact_method", selected.preferred_contact_method || "phone"], ["marketing_notifications", Boolean(selected.marketing_notifications)], ["service_notifications", Boolean(selected.service_notifications)], ["reward_points", Number(selected.reward_points || 0)]]); const updated = await api<Row>(`api/v1/admin/profiles/${selected.id}`, { method: "PATCH", body: JSON.stringify(payload) }); setRows((current) => current.map((row) => row.id === updated.id ? updated : row)); setSelected(updated); setMessage("اطلاعات کاربر ذخیره شد."); } catch (e) { setMessage(e instanceof ApiError ? e.message : "ذخیره انجام نشد."); } finally { setSaving(false); } }
  return <div className="space-y-6"><header><p className="text-sm font-bold text-primary">مدیریت کاربران</p><h1 className="mt-2 text-3xl font-black">اطلاعات و پروفایل کاربران</h1><p className="mt-2 text-muted-foreground">جست‌وجو، مشاهده و ویرایش اطلاعات تماس، نشانی، کسب‌وکار و امتیاز کاربران.</p></header>{message && <p className="rounded-xl bg-blue-50 p-3 text-sm text-blue-800">{message}</p>}<div className="relative max-w-xl"><Search className="absolute right-3 top-3 size-4 text-muted-foreground" /><Input className="pr-10" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="جست‌وجو با نام، ایمیل، موبایل یا کسب‌وکار" /></div>
    <div className="grid gap-4 xl:grid-cols-2">{filtered.map((row) => <Card key={row.id} className="border-blue-100"><CardContent className="flex flex-wrap items-center justify-between gap-4 p-5"><div><div className="flex items-center gap-2"><b>{row.full_name}</b><Badge variant="outline">{row.tier}</Badge>{!row.is_active && <Badge variant="destructive">غیرفعال</Badge>}</div><p className="mt-2 text-sm text-muted-foreground" dir="ltr">{row.email}</p><p className="mt-1 text-sm">{String(row.phone || "بدون شماره")} · {[row.province,row.city].filter(Boolean).join("، ") || "موقعیت ثبت نشده"}</p><p className="mt-2 text-xs text-muted-foreground">تکمیل {row.profile_score.toLocaleString("fa-IR")}٪ · {row.reward_points.toLocaleString("fa-IR")} امتیاز</p></div><Button variant="outline" onClick={() => { setSelected(row); setMessage(""); }}><Edit3 />جزئیات و ویرایش</Button></CardContent></Card>)}</div>
    {!filtered.length && <div className="rounded-3xl border border-dashed p-12 text-center text-muted-foreground"><UserRoundSearch className="mx-auto mb-3 size-9" />کاربری پیدا نشد.</div>}
    {selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/45 p-4" onMouseDown={(e) => { if (e.target === e.currentTarget) setSelected(null); }}><Card className="max-h-[92vh] w-full max-w-4xl overflow-y-auto"><CardHeader className="sticky top-0 z-10 flex-row items-center justify-between border-b bg-white"><div><CardTitle>{selected.full_name}</CardTitle><p className="mt-1 text-sm text-muted-foreground" dir="ltr">{selected.email}</p></div><Button variant="ghost" size="icon" onClick={() => setSelected(null)}><X /></Button></CardHeader><CardContent className="grid gap-4 p-6 md:grid-cols-2">{editable.map(([key,label]) => <label key={key} className="space-y-2 text-sm"><span>{label}</span><Input type={key === "birth_date" ? "date" : "text"} value={String(selected[key] || "")} onChange={(e) => change(key, e.target.value)} /></label>)}<label className="space-y-2 text-sm"><span>نوع مؤدی</span><select className="h-10 w-full rounded-lg border bg-white px-3" value={String(selected.taxpayer_type || "individual")} onChange={(e) => change("taxpayer_type", e.target.value)}><option value="individual">شخص حقیقی</option><option value="company">شخص حقوقی</option></select></label><label className="space-y-2 text-sm"><span>امتیاز وفاداری</span><Input type="number" min="0" value={Number(selected.reward_points || 0)} onChange={(e) => change("reward_points", Number(e.target.value))} /></label><label className="space-y-2 text-sm md:col-span-2"><span>نشانی کامل</span><Textarea value={String(selected.address || "")} onChange={(e) => change("address", e.target.value)} /></label><label className="space-y-2 text-sm md:col-span-2"><span>درباره کاربر و نیاز مالیاتی</span><Textarea value={String(selected.bio || "")} onChange={(e) => change("bio", e.target.value)} /></label><div className="flex flex-wrap gap-4 md:col-span-2"><label className="flex items-center gap-2"><input type="checkbox" checked={Boolean(selected.service_notifications)} onChange={(e) => change("service_notifications", e.target.checked)} />اعلان‌های ضروری</label><label className="flex items-center gap-2"><input type="checkbox" checked={Boolean(selected.marketing_notifications)} onChange={(e) => change("marketing_notifications", e.target.checked)} />پیام‌های پیشنهادی</label></div><Button className="md:col-span-2" disabled={saving} onClick={save}>{saving ? "در حال ذخیره..." : "ذخیره تغییرات"}</Button></CardContent></Card></div>}
  </div>;
}
