"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, BadgeCheck, BarChart3, BookOpen, BookOpenCheck, CalendarDays, CheckCircle2, Headphones, MessageCircleQuestion, Sparkles, TicketCheck, UploadCloud, UserRoundCheck, WalletCards, Wrench } from "lucide-react";
import { api } from "@/lib/api";
import type { Consultation, Conversation, User } from "@/lib/types";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";

const services = [
  { href: "/app/chat", title: "دستیار مالیاتی", text: "پاسخ کوتاه و ساده برای پرسش‌های مالیاتی", icon: MessageCircleQuestion, color: "from-blue-600 to-cyan-500", soft: "bg-blue-100 text-blue-700" },
  { href: "/app/tools", title: "ابزارهای مالیاتی", text: "محاسبه و ساخت پیش‌نویس‌های کاربردی", icon: Wrench, color: "from-amber-400 to-orange-500", soft: "bg-amber-100 text-amber-700" },
  { href: "/app/documents", title: "اسناد و مدارک", text: "بارگذاری و پیگیری امن مدارک پرونده", icon: UploadCloud, color: "from-emerald-500 to-teal-400", soft: "bg-emerald-100 text-emerald-700" },
  { href: "/app/consultations", title: "مرکز مشاوران", text: "مشاوره آنلاین یا حضوری با متخصصان تأییدشده", icon: Headphones, color: "from-rose-500 to-orange-400", soft: "bg-rose-100 text-rose-700" },
  { href: "/app/calendar", title: "تقویم مالیاتی", text: "مدیریت موعدها و یادآوری تکالیف", icon: CalendarDays, color: "from-cyan-500 to-sky-500", soft: "bg-cyan-100 text-cyan-700" },
  { href: "/app/tickets", title: "مرکز پشتیبانی", text: "ثبت و پیگیری تیکت‌های حساب", icon: TicketCheck, color: "from-indigo-500 to-blue-500", soft: "bg-indigo-100 text-indigo-700" },
  { href: "/app/plans", title: "اشتراک چکاه", text: "مشاهده امکانات و ارتقای ظرفیت", icon: Sparkles, color: "from-fuchsia-500 to-rose-500", soft: "bg-fuchsia-100 text-fuchsia-700" },
  { href: "/app/wallet", title: "کیف پول", text: "شارژ، برداشت و مشاهده تراکنش‌ها", icon: WalletCards, color: "from-sky-500 to-blue-600", soft: "bg-sky-100 text-sky-700" },
];

export default function DashboardPage() {
  const [user, setUser] = useState<User | null>(null);
  const [conversations, setConversations] = useState<Conversation[]>([]);
  const [consultations, setConsultations] = useState<Consultation[]>([]);
  useEffect(() => { Promise.all([api<User>("users/me"), api<Conversation[]>("api/v1/conversations"), api<Consultation[]>("api/v1/consultations")]).then(([currentUser, chats, requests]) => { setUser(currentUser); setConversations(chats); setConsultations(requests); }).catch(() => null); }, []);

  return <div className="space-y-10">
    <section className="relative overflow-hidden rounded-[2.25rem] bg-gradient-to-l from-blue-700 via-blue-600 to-cyan-500 px-6 py-10 text-white shadow-2xl shadow-blue-900/15 sm:px-10 sm:py-14"><div className="absolute -left-20 -top-24 size-72 rounded-full bg-white/10" /><div className="absolute -bottom-32 right-1/3 size-72 rounded-full bg-cyan-200/10" /><div className="relative grid items-center gap-8 lg:grid-cols-[1fr_.55fr]"><div><p className="flex items-center gap-2 text-sm text-cyan-50"><Sparkles className="size-4" /> همراه هوشمند امور مالیاتی</p><h1 className="mt-4 text-3xl font-black leading-[1.5] sm:text-4xl">سلام {user?.full_name?.split(" ")[0] ?? ""}؛ امروز چه کاری برایتان انجام دهیم؟</h1><p className="mt-4 max-w-2xl leading-8 text-blue-50">از پرسیدن سؤال تا محاسبه، ارسال سند و ارتباط با کارشناس؛ همه خدمات چکاه از همین صفحه در دسترس شماست.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/app/chat" className="flex items-center gap-2 rounded-2xl bg-white px-6 py-3 font-bold text-blue-700 shadow-xl">شروع گفت‌وگو <ArrowLeft className="size-4" /></Link><Link href="/app/tools" className="rounded-2xl border border-white/30 bg-white/10 px-6 py-3 font-bold backdrop-blur">مشاهده ابزارها</Link></div></div><div className="grid grid-cols-2 gap-3"><HeroStat label="گفتگو" value={conversations.length} icon={MessageCircleQuestion} /><HeroStat label="درخواست تخصصی" value={consultations.length} icon={UserRoundCheck} /><HeroStat label="وضعیت حساب" value="فعال" icon={CheckCircle2} /><HeroStat label="پاسخ‌ها" value="مستند" icon={BookOpenCheck} /></div></div></section>

    <section className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><Link href="/app/laws" className="group relative min-h-64 overflow-hidden rounded-[2rem] bg-gradient-to-l from-blue-700 via-blue-600 to-cyan-500 p-7 text-white shadow-xl shadow-blue-900/15 transition hover:-translate-y-1 hover:shadow-2xl"><div className="absolute -left-12 -top-16 size-48 rounded-full bg-white/10" /><div className="relative flex h-full flex-col justify-between gap-8"><div><span className="flex size-14 items-center justify-center rounded-2xl bg-white/15 backdrop-blur"><BookOpen /></span><p className="mt-5 text-xs font-bold text-cyan-100">دسترسی اصلی</p><h2 className="mt-1 text-2xl font-black">مرکز قوانین و مقررات</h2><p className="mt-3 max-w-xl text-sm leading-7 text-blue-50">قوانین، مواد و تبصره‌های مالیاتی را مستقیم و سریع جست‌وجو کنید.</p></div><span className="flex w-fit items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-blue-700">ورود به مرکز قوانین <ArrowLeft className="size-4 transition group-hover:-translate-x-1" /></span></div></Link><Link href="/app/consultant-verification" className="group flex min-h-64 flex-col justify-between rounded-[2rem] border border-sky-200 bg-gradient-to-br from-white to-sky-50 p-7 shadow-lg shadow-blue-900/5 transition hover:-translate-y-1 hover:border-blue-300 hover:shadow-xl"><div><span className="flex size-14 items-center justify-center rounded-2xl bg-blue-100 text-blue-700"><BadgeCheck /></span><p className="mt-5 text-xs font-bold text-blue-600">فرصت همکاری حرفه‌ای</p><h2 className="mt-1 text-xl font-black">همکاری به‌عنوان مشاور</h2><p className="mt-3 text-sm leading-7 text-slate-600">تخصص و مدارک خود را ثبت کنید و به شبکه مشاوران چکاه بپیوندید.</p></div><span className="mt-6 flex w-fit items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white">ثبت درخواست <ArrowLeft className="size-4 transition group-hover:-translate-x-1" /></span></Link></section>

    <section><div className="mb-5 flex items-end justify-between"><div><p className="text-sm font-bold text-blue-600">خدمات یکپارچه</p><h2 className="mt-1 text-2xl font-black">همه‌چیز در یک نگاه</h2></div><Link href="/app/usage" className="hidden items-center gap-2 text-sm font-bold text-blue-600 sm:flex"><BarChart3 className="size-4" /> گزارش مصرف</Link></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{services.map((service) => <Link href={service.href} key={service.href} className="group relative overflow-hidden rounded-3xl border border-sky-100 bg-white p-5 shadow-lg shadow-blue-900/5 transition hover:-translate-y-1.5 hover:border-blue-200 hover:shadow-2xl"><div className={`absolute inset-x-0 top-0 h-1.5 bg-gradient-to-l ${service.color}`} /><span className={`flex size-12 items-center justify-center rounded-2xl ${service.soft}`}><service.icon /></span><h3 className="mt-5 text-lg font-black">{service.title}</h3><p className="mt-2 min-h-12 text-sm leading-6 text-slate-500">{service.text}</p><span className="mt-5 flex items-center gap-2 text-xs font-bold text-blue-600">ورود به بخش <ArrowLeft className="size-3.5 transition group-hover:-translate-x-1" /></span></Link>)}</div></section>

    <section className="grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><Card className="border-sky-100 bg-white shadow-lg shadow-slate-900/5"><CardHeader><CardTitle>گفتگوهای اخیر</CardTitle><CardDescription>ادامه سریع آخرین پرسش‌های شما</CardDescription></CardHeader><CardContent className="space-y-2">{!user ? <><Skeleton className="h-16" /><Skeleton className="h-16" /></> : conversations.length ? conversations.slice(0, 4).map((item) => <Link key={item.id} href={`/app/chat?conversation=${item.id}`} className="flex items-center justify-between rounded-2xl border border-sky-50 bg-sky-50/40 p-4 transition hover:border-sky-200 hover:bg-sky-50"><div><p className="font-medium">{item.title}</p><p className="mt-1 text-xs text-slate-400">{new Date(item.updated_at).toLocaleDateString("fa-IR")}</p></div><ArrowLeft className="size-4 text-blue-500" /></Link>) : <div className="rounded-2xl border border-dashed border-sky-200 p-9 text-center text-sm text-slate-500">هنوز گفت‌وگویی ثبت نشده است.</div>}</CardContent></Card><div className="rounded-3xl border border-sky-100 bg-gradient-to-br from-blue-50 to-cyan-50 p-6 shadow-lg shadow-blue-900/5"><span className="flex size-12 items-center justify-center rounded-2xl bg-white text-blue-600 shadow-sm"><Sparkles /></span><h2 className="mt-5 text-xl font-black">ظرفیت بیشتری نیاز دارید؟</h2><p className="mt-3 text-sm leading-7 text-slate-600">با ارتقای پلن، پیام، ابزار، آپلود و پشتیبانی بیشتری در اختیار دارید.</p><Link href="/app/plans" className="mt-6 flex items-center justify-center gap-2 rounded-2xl bg-blue-600 px-5 py-3 text-sm font-bold text-white">مشاهده پلن‌ها <ArrowLeft className="size-4" /></Link></div></section>
  </div>;
}

function HeroStat({ label, value, icon: Icon }: { label: string; value: string | number; icon: typeof MessageCircleQuestion }) { return <div className="rounded-2xl border border-white/15 bg-white/10 p-4 backdrop-blur"><Icon className="size-5 text-cyan-100" /><p className="mt-4 text-2xl font-black">{value}</p><p className="mt-1 text-xs text-blue-100">{label}</p></div>; }
