import type { Metadata } from "next";
import Link from "next/link";
import { cookies } from "next/headers";
import { Check, HelpCircle } from "lucide-react";
import { PublicFooter } from "@/components/public-footer";
import { PublicHeader } from "@/components/public-header";
import { accessCookie, refreshCookie } from "@/lib/backend";

export const metadata: Metadata = { title: "تعرفه و پلن‌های اشتراک", description: "مقایسه امکانات پلن‌های عادی، پلاس و حرفه‌ای چکاه" };
const plans = [
  { code: "normal", title: "عادی", price: "رایگان", description: "برای آشنایی و استفاده محدود", benefits: ["۱۰ پرسش هوشمند", "۵ جست‌وجوی قانون", "۱۰ محاسبه مالیاتی", "یک سند و یک درخواست پشتیبانی"] },
  { code: "plus", title: "پلاس", price: "از ۱۴۹ هزار تومان", description: "برای مؤدیان و کسب‌وکارهای کوچک", popular: true, benefits: ["۱۰۰ پرسش هوشمند", "۱۰۰ جست‌وجوی قانون و محاسبه", "۵ سند و ۱۰ پیش‌نویس نامه", "پشتیبانی و امکان رزرو مشاور"] },
  { code: "pro", title: "حرفه‌ای", price: "از ۵۴۹ هزار تومان", description: "برای استفاده حرفه‌ای و پرتکرار", benefits: ["۱۰۰۰ پرسش و جست‌وجوی قانون", "ظرفیت حرفه‌ای ابزارها", "۲۰ سند و ۱۰۰ پیش‌نویس نامه", "سهمیه بیشتر پشتیبانی و مشاوره"] },
];

export default async function PricingPage() { const store = await cookies(); const loggedIn = store.has(accessCookie) || store.has(refreshCookie); return <main><PublicHeader /><section className="mx-auto max-w-6xl px-5 py-14 text-center"><p className="font-bold text-blue-600">شفاف، قابل ارتقا و بدون خروج از حساب</p><h1 className="mt-3 text-4xl font-black">پلن مناسب نیاز مالیاتی شما</h1><p className="mx-auto mt-4 max-w-2xl text-sm leading-8 text-slate-600">پلن‌ها در تعداد استفاده از دستیار، قوانین، اسناد و خدمات پشتیبانی تفاوت دارند. ورود به این صفحه وضعیت حساب شما را تغییر نمی‌دهد.</p><div className="mt-10 grid gap-5 md:grid-cols-3">{plans.map((plan) => <article key={plan.code} className={`relative rounded-3xl border bg-white p-7 text-right shadow-sm ${plan.popular ? "border-blue-500 shadow-lg shadow-blue-500/10" : "border-slate-200"}`}>{plan.popular && <span className="absolute -top-3 right-6 rounded-full bg-blue-600 px-3 py-1 text-xs font-bold text-white">پیشنهاد محبوب</span>}<h2 className="text-2xl font-black">{plan.title}</h2><p className="mt-2 text-sm text-slate-500">{plan.description}</p><p className="mt-4 text-xl font-black text-blue-700">{plan.price}</p><ul className="mt-6 space-y-3 text-sm">{plan.benefits.map((benefit) => <li key={benefit} className="flex gap-2 leading-6"><Check className="mt-1 size-4 shrink-0 text-emerald-600" />{benefit}</li>)}</ul><Link href={loggedIn ? `/app/plans/${plan.code}` : `/login?next=${encodeURIComponent(`/app/plans/${plan.code}`)}`} className="mt-8 block rounded-xl bg-blue-600 px-4 py-3 text-center font-bold text-white">{loggedIn ? "انتخاب و مدیریت پلن" : "ورود و انتخاب پلن"}</Link></article>)}</div><div className="mx-auto mt-10 flex max-w-3xl gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-right"><HelpCircle className="mt-1 shrink-0 text-amber-700" /><p className="text-sm leading-7 text-amber-900">مبالغ نهایی و دوره‌های قابل خرید در مرحله انتخاب پلن نمایش داده می‌شوند. خرید اشتراک به‌معنای تضمین نتیجه یک پرونده مالیاتی نیست.</p></div></section><PublicFooter /></main>; }
