"""add document ingestion models

Revision ID: f1d3869b502b
Revises: 0003_add_account_tiers
Create Date: 2026-07-14 15:16:28.086605
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "f1d3869b502b"
down_revision: Union[str, None] = "0003_add_account_tiers"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("document_type", sa.String(length=50), nullable=False),
        sa.Column("issuing_authority", sa.String(length=200), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_documents_created_by"), "documents", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_documents_document_type"), "documents", ["document_type"], unique=False
    )
    op.create_index(op.f("ix_documents_title"), "documents", ["title"], unique=False)
    op.create_table(
        "document_topics",
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("topic", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("document_id", "topic"),
    )
    op.create_table(
        "document_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default="uploaded", nullable=False
        ),
        sa.Column("extracted_text", sa.Text(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column(
            "lifecycle_status",
            sa.String(length=20),
            server_default="draft",
            nullable=False,
        ),
        sa.Column(
            "review_status",
            sa.String(length=20),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "lifecycle_status IN ('draft','active','amended','repealed','archived')",
            name="ck_document_versions_lifecycle_status",
        ),
        sa.CheckConstraint(
            "review_status IN ('pending','approved','rejected')",
            name="ck_document_versions_review_status",
        ),
        sa.CheckConstraint(
            "status IN ('uploaded','queued','extracting','extracted','chunking','embedding','needs_review','ready','failed')",
            name="ck_document_versions_status",
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from",
            name="ck_document_versions_validity_range",
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_id", "version_number", name="uq_document_version_number"
        ),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(
        op.f("ix_document_versions_document_id"),
        "document_versions",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_versions_file_hash"),
        "document_versions",
        ["file_hash"],
        unique=False,
    )
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_version_id", sa.String(length=36), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("article_number", sa.String(length=50), nullable=True),
        sa.Column("section_title", sa.String(length=300), nullable=True),
        sa.Column("char_count", sa.Integer(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_version_id"], ["document_versions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_version_id", "chunk_index", name="uq_version_chunk_index"
        ),
    )
    op.create_index(
        "ix_chunks_article_number", "document_chunks", ["article_number"], unique=False
    )
    op.create_index(
        op.f("ix_document_chunks_content_hash"),
        "document_chunks",
        ["content_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_chunks_document_version_id"),
        "document_chunks",
        ["document_version_id"],
        unique=False,
    )
    op.create_table(
        "document_processing_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_version_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="queued", nullable=False
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued','running','succeeded','failed')",
            name="ck_document_jobs_status",
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"], ["document_versions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_processing_jobs_document_version_id"),
        "document_processing_jobs",
        ["document_version_id"],
        unique=False,
    )
    op.create_table(
        "document_relations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_version_id", sa.String(length=36), nullable=False),
        sa.Column("target_version_id", sa.String(length=36), nullable=False),
        sa.Column("relation_type", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "relation_type IN ('amends','repeals','supersedes','related')",
            name="ck_document_relations_type",
        ),
        sa.ForeignKeyConstraint(
            ["source_version_id"], ["document_versions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["target_version_id"], ["document_versions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_version_id",
            "target_version_id",
            "relation_type",
            name="uq_document_relation",
        ),
    )
    op.create_index(
        op.f("ix_document_relations_source_version_id"),
        "document_relations",
        ["source_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_relations_target_version_id"),
        "document_relations",
        ["target_version_id"],
        unique=False,
    )
    op.create_table(
        "document_reviews",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_version_id", sa.String(length=36), nullable=False),
        sa.Column("reviewer_user_id", sa.String(length=36), nullable=False),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column("note", sa.String(length=1000), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "decision IN ('approved','rejected')", name="ck_document_reviews_decision"
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"], ["document_versions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_reviews_document_version_id"),
        "document_reviews",
        ["document_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_reviews_reviewer_user_id"),
        "document_reviews",
        ["reviewer_user_id"],
        unique=False,
    )
    permissions_table = sa.table(
        "permissions",
        sa.column("id", sa.Integer()),
        sa.column("code", sa.String()),
        sa.column("description", sa.String()),
    )
    role_permissions_table = sa.table(
        "role_permissions",
        sa.column("role_id", sa.Integer()),
        sa.column("permission_id", sa.Integer()),
    )
    op.bulk_insert(
        permissions_table,
        [{"id": 8, "code": "documents:review", "description": "documents review"}],
    )
    op.bulk_insert(
        role_permissions_table,
        [
            {"role_id": 2, "permission_id": 8},
            {"role_id": 3, "permission_id": 8},
            {"role_id": 4, "permission_id": 8},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("DELETE FROM role_permissions WHERE permission_id = 8"))
    op.execute(
        sa.text("DELETE FROM permissions WHERE id = 8 AND code = 'documents:review'")
    )
    op.drop_index(
        op.f("ix_document_reviews_reviewer_user_id"), table_name="document_reviews"
    )
    op.drop_index(
        op.f("ix_document_reviews_document_version_id"), table_name="document_reviews"
    )
    op.drop_table("document_reviews")
    op.drop_index(
        op.f("ix_document_relations_target_version_id"), table_name="document_relations"
    )
    op.drop_index(
        op.f("ix_document_relations_source_version_id"), table_name="document_relations"
    )
    op.drop_table("document_relations")
    op.drop_index(
        op.f("ix_document_processing_jobs_document_version_id"),
        table_name="document_processing_jobs",
    )
    op.drop_table("document_processing_jobs")
    op.drop_index(
        op.f("ix_document_chunks_document_version_id"), table_name="document_chunks"
    )
    op.drop_index(op.f("ix_document_chunks_content_hash"), table_name="document_chunks")
    op.drop_index("ix_chunks_article_number", table_name="document_chunks")
    op.drop_table("document_chunks")
    op.drop_index(
        op.f("ix_document_versions_file_hash"), table_name="document_versions"
    )
    op.drop_index(
        op.f("ix_document_versions_document_id"), table_name="document_versions"
    )
    op.drop_table("document_versions")
    op.drop_table("document_topics")
    op.drop_index(op.f("ix_documents_title"), table_name="documents")
    op.drop_index(op.f("ix_documents_document_type"), table_name="documents")
    op.drop_index(op.f("ix_documents_created_by"), table_name="documents")
    op.drop_table("documents")
    # ### end Alembic commands ###
