"use client";

import { useEffect, useState } from "react";
import { BarChart3, Bot, CreditCard, FileStack, MessageCircle, ShieldCheck, TicketCheck, Users, WalletCards } from "lucide-react";
import { api } from "@/lib/api";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

type Stats = { users: number; payments: number; revenue: number; active_subscriptions: number; open_tickets: number; user_documents: number; conversations: number };
type Analytics = { tiers: Record<string, number>; two_factor_users: number; monthly_questions: number; monthly_revenue: number; pending_reminders: number };

export default function AdminHome() {
  const [stats, setStats] = useState<Stats | null>(null); const [analytics, setAnalytics] = useState<Analytics | null>(null);
  useEffect(() => { Promise.all([api<Stats>("api/v1/admin/summary"), api<Analytics>("api/v1/admin/analytics")]).then(([summary, report]) => { setStats(summary); setAnalytics(report); }); }, []);
  const cards = [[Users, "کاربران", stats?.users ?? 0], [WalletCards, "درآمد ثبت‌شده", `${(stats?.revenue ?? 0).toLocaleString("fa-IR")} تومان`], [CreditCard, "اشتراک فعال", stats?.active_subscriptions ?? 0], [TicketCheck, "تیکت باز", stats?.open_tickets ?? 0], [FileStack, "اسناد کاربران", stats?.user_documents ?? 0], [MessageCircle, "گفتگوها", stats?.conversations ?? 0]] as const;
  return <div className="space-y-8"><header className="relative overflow-hidden rounded-3xl bg-gradient-to-l from-blue-700 via-blue-600 to-cyan-500 p-8 text-white shadow-xl shadow-blue-900/15"><div className="absolute -left-16 -top-20 size-56 rounded-full bg-white/10" /><div className="relative"><p className="text-sm text-cyan-100">مرکز فرمان سامانه</p><h1 className="mt-2 text-3xl font-black">تحلیل و مدیریت</h1><p className="mt-3 text-blue-50">وضعیت کاربران، درآمد، امنیت و مصرف سامانه در یک نگاه.</p></div></header><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([Icon, label, value]) => <Card key={label} className="border-white/70 bg-white/85 transition hover:-translate-y-1 hover:shadow-lg"><CardContent className="flex items-center gap-4 p-6"><span className="flex size-13 items-center justify-center rounded-2xl bg-primary/10 text-primary"><Icon /></span><div><p className="text-2xl font-black">{value}</p><p className="text-sm text-muted-foreground">{label}</p></div></CardContent></Card>)}</section><div className="grid gap-6 lg:grid-cols-[1.25fr_.75fr]"><Card className="border-white/70 bg-white/85"><CardHeader><CardTitle className="flex gap-2"><BarChart3 className="text-primary" /> توزیع پلن‌ها</CardTitle><CardDescription>ترکیب کاربران عادی، پلاس و حرفه‌ای</CardDescription></CardHeader><CardContent className="space-y-4">{[["normal", "عادی"], ["plus", "پلاس"], ["pro", "حرفه‌ای"]].map(([key, label]) => { const count = analytics?.tiers[key] ?? 0; const percent = stats?.users ? count / stats.users * 100 : 0; return <div key={key}><div className="flex justify-between text-sm"><span>{label}</span><span>{count.toLocaleString("fa-IR")} کاربر</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-primary" style={{ width: `${percent}%` }} /></div></div>; })}</CardContent></Card><Card className="border-0 bg-gradient-to-br from-blue-600 to-cyan-500 text-white"><CardHeader><CardTitle>عملکرد این ماه</CardTitle></CardHeader><CardContent className="space-y-4"><Metric icon={WalletCards} label="درآمد ماه" value={`${(analytics?.monthly_revenue ?? 0).toLocaleString("fa-IR")} تومان`} /><Metric icon={Bot} label="پرسش کاربران" value={(analytics?.monthly_questions ?? 0).toLocaleString("fa-IR")} /><Metric icon={ShieldCheck} label="کاربران دومرحله‌ای" value={(analytics?.two_factor_users ?? 0).toLocaleString("fa-IR")} /></CardContent></Card></div></div>;
}

function Metric({ icon: Icon, label, value }: { icon: typeof Users; label: string; value: string }) { return <div className="flex items-center gap-3 rounded-xl bg-white/10 p-3"><Icon className="size-5" /><div><p className="font-bold">{value}</p><p className="text-xs text-white/70">{label}</p></div></div>; }
