"use client";

import Link from "next/link";
import { use, useEffect, useState } from "react";
import { ArrowRight, CreditCard, FileText, MessageCircle, Save, ShieldCheck, TicketCheck, WalletCards } from "lucide-react";
import { api, ApiError } from "@/lib/api";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

type Overview = { account:{id:string;full_name:string;email:string;tier:"normal"|"plus"|"pro";is_active:boolean;two_factor_enabled:boolean;roles:string[];created_at:string;last_seen_at:string|null}; profile:Record<string,string|number|boolean|null>; wallet:{balance:number;transactions:Array<{id:string;type:string;amount:number;status:string;reference:string;created_at:string}>}; subscriptions:Array<{id:string;title:string;package:string;status:string;starts_at:string;ends_at:string}>; payments:Array<{id:string;amount:number;status:string;reference:string;created_at:string}>; activity:{documents:number;tickets:number;conversations:number;consultations:number} };
const fields = [["phone","موبایل"],["alternate_phone","تماس جایگزین"],["alternate_email","ایمیل اختیاری"],["province","استان"],["city","شهر"],["postal_code","کد پستی"],["birth_date","تاریخ تولد"],["company_name","شرکت یا کسب‌وکار"],["job_title","عنوان شغلی"],["business_type","نوع فعالیت"],["economic_code","کد اقتصادی"],["website","وب‌سایت"]] as const;

export default function UserDetailsPage({params}:{params:Promise<{id:string}>}) {
  const {id}=use(params); const [data,setData]=useState<Overview|null>(null); const [message,setMessage]=useState(""); const [saving,setSaving]=useState(false);
  async function load(){try{setData(await api<Overview>(`api/v1/admin/users/${id}/overview`));}catch(reason){setMessage(reason instanceof ApiError?reason.message:"دریافت اطلاعات کاربر ممکن نیست.");}}
  useEffect(()=>{let active=true;api<Overview>(`api/v1/admin/users/${id}/overview`).then((result)=>{if(active)setData(result);}).catch((reason)=>{if(active)setMessage(reason instanceof ApiError?reason.message:"دریافت اطلاعات کاربر ممکن نیست.");});return()=>{active=false;};},[id]);
  function profile(key:string,value:string|number|boolean|null){setData((current)=>current?{...current,profile:{...current.profile,[key]:value}}:current);}
  function account(key:string,value:string|boolean|string[]){setData((current)=>current?{...current,account:{...current.account,[key]:value}}:current);}
  async function save(){if(!data)return;setSaving(true);setMessage("");try{await api(`users/${id}`,{method:"PATCH",body:JSON.stringify({account_tier:data.account.tier,is_active:data.account.is_active,roles:data.account.roles})});const payload={...data.profile,phone:data.profile.phone||"",alternate_phone:data.profile.alternate_phone||"",alternate_email:data.profile.alternate_email||null,province:data.profile.province||"",city:data.profile.city||"",postal_code:data.profile.postal_code||"",address:data.profile.address||"",birth_date:data.profile.birth_date||null,company_name:data.profile.company_name||"",job_title:data.profile.job_title||"",business_type:data.profile.business_type||"",economic_code:data.profile.economic_code||"",website:data.profile.website||"",taxpayer_type:data.profile.taxpayer_type||"individual",preferred_contact_method:data.profile.preferred_contact_method||"phone",marketing_notifications:Boolean(data.profile.marketing_notifications),service_notifications:Boolean(data.profile.service_notifications),bio:data.profile.bio||"",reward_points:Number(data.profile.reward_points||0)};await api(`api/v1/admin/profiles/${id}`,{method:"PATCH",body:JSON.stringify(payload)});setMessage("همه تغییرات کاربر ذخیره شد.");await load();}catch(reason){setMessage(reason instanceof ApiError?reason.message:"ذخیره تغییرات انجام نشد.");}finally{setSaving(false);}}
  if(!data)return <div className="p-12 text-center">{message||"در حال دریافت اطلاعات کاربر..."}</div>;
  const role=data.account.roles[0]||"user";
  return <div className="space-y-6"><Link href="/management/users" className="flex items-center gap-2 text-sm text-blue-600"><ArrowRight className="size-4"/>بازگشت به کاربران</Link><header className="flex flex-wrap items-center justify-between gap-4 rounded-3xl bg-gradient-to-l from-blue-700 to-cyan-500 p-6 text-white"><div><h1 className="text-3xl font-black">{data.account.full_name}</h1><p className="mt-2" dir="ltr">{data.account.email}</p><p className="mt-2 text-xs text-blue-100">عضویت از {new Date(data.account.created_at).toLocaleDateString("fa-IR")}</p></div><div className="text-left"><p className="text-sm text-blue-100">موجودی کیف پول</p><p className="mt-1 text-2xl font-black">{data.wallet.balance.toLocaleString("fa-IR")} تومان</p></div></header>{message&&<p className="rounded-xl bg-blue-50 p-4 text-sm text-blue-800">{message}</p>}
    <div className="grid gap-4 sm:grid-cols-4"><Metric icon={FileText} label="اسناد" value={data.activity.documents}/><Metric icon={TicketCheck} label="تیکت‌ها" value={data.activity.tickets}/><Metric icon={MessageCircle} label="گفتگوها" value={data.activity.conversations}/><Metric icon={CreditCard} label="پرداخت‌ها" value={data.payments.length}/></div>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="text-blue-600"/>حساب و دسترسی</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-4"><label className="space-y-2 text-sm"><span>نام کامل</span><Input value={data.account.full_name} disabled/></label><label className="space-y-2 text-sm"><span>نقش اصلی</span><select className="h-10 w-full rounded-lg border bg-white px-3" value={role} onChange={(event)=>account("roles",[event.target.value])}><option value="user">کاربر</option><option value="admin">ادمین</option><option value="tax_expert">کارشناس مالی</option><option value="company_expert">کارشناس شرکت</option><option value="system_admin">مدیر سامانه</option></select></label><label className="space-y-2 text-sm"><span>پلن</span><select className="h-10 w-full rounded-lg border bg-white px-3" value={data.account.tier} onChange={(event)=>account("tier",event.target.value)}><option value="normal">عادی</option><option value="plus">پلاس</option><option value="pro">حرفه‌ای</option></select></label><label className="flex items-center gap-2 rounded-xl border p-3 text-sm"><input type="checkbox" checked={data.account.is_active} onChange={(event)=>account("is_active",event.target.checked)}/>حساب فعال باشد</label></CardContent></Card>
    <Card><CardHeader><CardTitle>پروفایل و اطلاعات تماس</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-2">{fields.map(([key,label])=><label key={key} className="space-y-2 text-sm"><span>{label}</span><Input type={key==="birth_date"?"date":"text"} value={String(data.profile[key]||"")} onChange={(event)=>profile(key,event.target.value)}/></label>)}<label className="space-y-2 text-sm"><span>نوع مؤدی</span><select className="h-10 w-full rounded-lg border bg-white px-3" value={String(data.profile.taxpayer_type||"individual")} onChange={(event)=>profile("taxpayer_type",event.target.value)}><option value="individual">شخص حقیقی</option><option value="company">شخص حقوقی</option></select></label><label className="space-y-2 text-sm"><span>امتیاز وفاداری</span><Input type="number" min="0" value={Number(data.profile.reward_points||0)} onChange={(event)=>profile("reward_points",Number(event.target.value))}/></label><label className="space-y-2 text-sm md:col-span-2"><span>نشانی</span><Textarea value={String(data.profile.address||"")} onChange={(event)=>profile("address",event.target.value)}/></label><label className="space-y-2 text-sm md:col-span-2"><span>درباره فعالیت و نیازها</span><Textarea value={String(data.profile.bio||"")} onChange={(event)=>profile("bio",event.target.value)}/></label></CardContent></Card>
    <div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><WalletCards className="text-blue-600"/>گردش کیف پول</CardTitle></CardHeader><CardContent className="max-h-96 space-y-2 overflow-y-auto">{data.wallet.transactions.map((item)=><div key={item.id} className="flex justify-between rounded-xl border p-3 text-sm"><div><b>{item.type}</b><p className="text-xs text-muted-foreground" dir="ltr">{item.reference}</p></div><div className="text-left"><b>{item.amount.toLocaleString("fa-IR")} تومان</b><p className="text-xs text-muted-foreground">{item.status}</p></div></div>)}{!data.wallet.transactions.length&&<p className="text-sm text-muted-foreground">تراکنشی ثبت نشده است.</p>}</CardContent></Card><Card><CardHeader><CardTitle>اشتراک‌ها و پرداخت‌ها</CardTitle></CardHeader><CardContent className="space-y-3">{data.subscriptions.map((item)=><div key={item.id} className="rounded-xl border p-3"><div className="flex justify-between"><b>{item.title} · {item.package}</b><Badge>{item.status}</Badge></div><p className="mt-2 text-xs text-muted-foreground">تا {new Date(item.ends_at).toLocaleDateString("fa-IR")}</p></div>)}{!data.subscriptions.length&&<p className="text-sm text-muted-foreground">اشتراکی ثبت نشده است.</p>}</CardContent></Card></div>
    <div className="sticky bottom-4 z-10 flex justify-end"><Button size="lg" onClick={save} disabled={saving} className="min-w-48 shadow-xl"><Save/>{saving?"در حال ذخیره...":"ذخیره همه تغییرات"}</Button></div>
  </div>;
}
function Metric({icon:Icon,label,value}:{icon:typeof FileText;label:string;value:number}){return <Card><CardContent className="flex items-center gap-3 p-4"><Icon className="size-5 text-blue-600"/><div><b className="text-xl">{value.toLocaleString("fa-IR")}</b><p className="text-xs text-muted-foreground">{label}</p></div></CardContent></Card>}
